### ISSUE TITLE
Crash when hyperspace jump is made to another system (tested: Lave -> Diso)

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/newkind#2]
It seems, the problem is that "ship" type -1 denotes to the planet, and -2 to the star ("sun").  However dereferencing various stuffs for the "Sun" at update_universe causes the problem. The "ship items" table is prepared for the -1 value (Planet) but it seems not so much for the Sun. I could solve the problem with assigning a positive item type for the Sun, then it does not crash any more, star is rendered, but I am not sure if it cause problem, or why it is important to have negative values for the astronomical objects, maybe there is impact of my try to assign a positive value.

I'm still getting familiar with the source, though ...

**Comment by lgblgblgb** [comment]
Commit 007244ee103571882f69c3bba3b58e7b6fca0eca

It does introduce HACKING_SUN_IS_POSITIVE if defined in Makefile for CC command line, "Sun" is given with a positive identifier. I cannot see crash or any other glitch here, but who knows, would be funny to destroy stars with energy bombs or such :-O

**Comment by cptnapalm** [comment]
I think it's a pecularity of -2 (the sun type) being bitwise ANDed with the explosion flag (4).  Two's complement means that the bitwise AND succeeds, so it tries to blow up the sun.  At any rate, checking for sun or planet before calling draw_explosion eliminated the problem for me.

**Comment by lgblgblgb** [comment]
So we've created a supernova just by being wrong about a bitwise operation, nice enough (Sam in StarGate is lame, she needed a star gate as well to do this, when an "AND" is enough) :-D Ok, sorry about my insane try here to be humorous ... Thanks for the explanation, interesting catch!

**Comment by TimSC** [comment]
The problem is caused by flags not being initialized in add_new_ship :) I fixed it in my branch https://gitlab.com/TimSC/newkind/

**Comment by lgblgblgb** [comment]
@TimSC thanks, yeah, it seems. I've quickly patched my tree with the modification I saw in your branch. Thanks!!!!!!!!!! It seems, even with my fix not making Sun negative by ID, there were random crashes, possible because of the missing initialization of flags, you mentioned. Now I haven't seen any crash since then. Cool!
